[tool.poetry]
name = "solis"
version = "0.1.0"
description = ""
authors = ["Mikkel Stårvik <mikkel.starvik@gmail.com>"]
readme = "README.md"

packages = [
    { include = "s2utils", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
affine = "^2.4.0"
fiona = "^1.9.5"
pyproj = "^3.6.1"
shapely = "^2.0.2"
zstandard = "^0.21.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"

[tool.pyright]
include = ["src"]
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
